#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ "$SHLVL" -eq 1 && ! -o LOGIN && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi

export MYDOTFILES="${HOME}/.dotfiles"

#powerline
POWERLINE_CONFIG_COMMAND="$MYDOTFILES/powerline/powerline/scripts/powerline-config"
if [ -x "${POWERLINE_CONFIG_COMMAND}" ] ; then
    export POWERLINE_CONFIG_COMMAND
    export POWERLINE_COMMAND="$MYDOTFILES/powerline/powerline/scripts/powerline"
fi

# initialise environment variables here
source "${HOME}/.early_fns"

source_overrides .early_fns
source_overrides .zshenv_early

export HOSTNAME=$( hostname )
export DOMAINNAME=$( perl -e "(\$_)= qq($HOSTNAME) =~ m|^[^.]+\.(.*)$|; print" )
case "${DOMAINNAME}" in
	*uncarved*)	DOMAINNAME="uncarved.com";;
esac

export OSTYPE=$( uname )

if [ -f /etc/java/java.conf ] ; then
	. /etc/java/java.conf
	export JAVA_HOME
	PATH=$JAVA_HOME/bin:$PATH
fi

# Unless we have some processes with a tty, assume that we want
# a login timeout and some rlimits.  (Purely for safety)
if [ -t 0 ] ; then
	export GOT_TTY
	GOT_TTY=$( ps auxww | awk "/awk/ {next} /^${USER}.* tty/ {print}" )
fi
if [ -n "${GOT_TTY}" ] ; then
	export CONSOLE_HOST="${HOSTNAME}"
else
	TMOUT=4500
	ulimit -St 3600
	ulimit -Sc 0
fi

#Tie colon-delimited paths to arrays and disallow duplicates
typeset -U manpath
typeset -U path
typeset -U fpath
typeset -U ld_library_path
typeset -U perl5lib
typeset -U perllib
typeset -U classpath
typeset -U pythonpath


if [[ "${ZSH_VERSION_TYPE}" == "new" ]] ; then
	typeset -T LD_LIBRARY_PATH ld_library_path
	typeset -T PERL5LIB perl5lib
	typeset -T PERLLIB perllib
	typeset -T CLASSPATH classpath
	typeset -T PYTHONPATH pythonpath
fi												

path_add /sbin /usr/sbin /usr/local/sbin /usr/X11R6/bin 
path_add_front /usr/local/bin "${HOME}/bin" "${HOME}/bin-${OSTYPE}" "${GOPATH}/bin"
general_path_add MANPATH /usr/local/share/man /usr/share/man /usr/man "${HOME}/share/man"

export VISUAL=$( which vim )
export EDITOR=$( which vim )
export PAGER=$( which less )

export INPUTRC="${HOME}/.inputrc"
export TMPDIR="${HOME}/tmp"
export TMP="${HOME}/tmp"
if [[ -d "${HOME}/mail/incoming/Maildir/" ]] ; then
    export MAILDIR="${HOME}/mail/incoming/Maildir/"
    export MAIL="${HOME}/mail/incoming/Maildir/"
fi

if [[ -z "${TZ}" ]] ; then
    export TZ=Europe/London
fi

export POWERLINE_CONFIG_COMMAND="${MYDOTFILES}/powerline/powerline/scripts/powerline-config"

export JAVA_TOOL_OPTIONS=-Dfile.encoding=UTF8
if [ -f "${HOME}/.sbtconfig" ] ; then
	. "${HOME}/.sbtconfig"
else
	SBT_OPTS="-Xms4G -Xmx8G -Xss1M -server -XX:+CMSClassUnloadingEnabled -XX:+UnlockExperimentalVMOptions -Dcom.sun.management.jmxremote"
fi
export SBT_OPTS

export HISTIGNORE="&:[bf]g:exit:cd:cd -:history"

setup_login_details
source_overrides .zshenv
