#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
if [[ -x dircolors ]] ; then
	if [[ -f 	"${HOME}/.dir_colors" ]] ; then
		eval $( dircolors "${HOME}/.dir_colors" )
	else
		eval $( dircolors -b )
	fi
fi

#irritating beeps?
setopt nobeep
#nice all background jobs automatically?
setopt bg_nice
#clobber files on redirect?
setopt noclobber
#prevent history search from finding duplicates?
setopt hist_find_no_dups
#ignore duplicate commands in shell history?
setopt hist_ignore_all_dups
#remove superfluous blanks from history?
setopt hist_reduce_blanks
#allow comments in interactive shells?
setopt interactive_comments
#make completion list smaller by using variable column sizes?
setopt list_packed
#allow pushd with no args to pushd $HOME?
#(otherwise swap with the top of dirstack)
setopt nopushd_to_home
#ignore duplicate dirs passed onto the dir stack?
setopt pushd_ignore_dups
#map ! in $PROMPT to the history number?
setopt prompt_bang
#hup background jobs on exit?  We can always use "nohup", "disown" or
#"&!" after the commands when we want to
setopt hup
#Allow multiple redirects and tees.  Warning, will make "foo 2>&1 > /dev/null | bar" fail
setopt no_multios
#Allow flow control?
setopt no_flow_control

#vi keybindings
#bindkey -v #done in zpreztorc
#I like to have these around as well as the vi command mode history searches
bindkey -M viins \^R history-incremental-search-backward
bindkey -M viins \^S history-incremental-search-forward
##I prefer the 'normal' versions of these (delete past the insertion point)
bindkey -rM viins '^H'
bindkey -M viins \^H backward-delete-char
bindkey -rM viins '^W'
bindkey -M viins \^W backward-delete-word
bindkey -M vicmd Q push-line
#note you can only bind ^Q if flow-control is off (setopt no_flow_control)
bindkey -M viins \^Q push-line
bindkey -rM viins \^V
bindkey -M viins \^V run-help

#Predictive text nonsense
autoload -U predict-on
zle -N predict-on
zle -N predict-off
bindkey -M viins "^X^Z" predict-on ## C-x C-z
bindkey -M viins "^Z" predict-off ## C-z

# Color definitions come in handy
autoload -U colors
colors

# Allow for functions in the prompt.
setopt PROMPT_SUBST

# Autoload zsh functions.
fpath=(~/.zsh/functions $fpath)
autoload -U ~/.zsh/functions/*(:t)

# Enable auto-execution of functions.
typeset -ga preexec_functions
typeset -ga precmd_functions
typeset -ga chpwd_functions

# Append git functions needed for prompt.
preexec_functions+='preexec_update_git_vars'
precmd_functions+='precmd_update_git_vars'
chpwd_functions+='chpwd_update_git_vars'

#where to save shell history
export HISTFILE=~/.zsh_history

#max number of history events to save
export SAVEHIST=1000

#only prompt if a list would scroll off the screen
export LISTMAX=0

#reporting timing of commands that take longer than this
export REPORTTIME=10

#watch and report the activities of other users
watch=notme
WATCHFMT='%D %T: %n has %a %l %(M.from %M.)'

. ~/.aliases
path_add /sbin /usr/sbin /usr/local/sbin /usr/X11R6/bin "${HOME}/bin" "${HOME}/bin-${OSTYPE}" /usr/local/opt/curl/bin
general_path_add MANPATH /usr/local/share/man /opt/diet/man /usr/share/man /usr/man

export PATH
export MANPATH

#output section
print_msg()
{
	if [[ -z "${SILENCE}" ]] ; then
		echo -n "[$@]"
	fi
}

nempty_print_msg()
{
	VAR=$1
	shift
	if [[ -n "${VAR}" ]] ; then
		print_msg $@
	fi
}

for v in "/usr/bin/virtualenvwrapper-3.sh" "/usr/local/bin/virtualenvwrapper.sh" "/usr/share/virtualenvwrapper/virtualenvwrapper.sh" ; do
    if [ -f "${v}" ] ; then
        source "${v}" >& /dev/null
        break
    fi
done

nempty_print_msg "${IN_A_SCREEN}" "screen from ${MY_LOGIN_HOST}"
nempty_print_msg "${SSH_AGENT_PID}" "ssh agent ${SSH_AGENT_PID}"
nempty_print_msg "${TMOUT}" "Timeout is ${TMOUT}s"
echo

#because flow control belongs to a bygone era
stty -ixon -ixoff

source_if "${HOME}/.fzf.zsh"
source_overrides .zshrc
